/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif




/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_acclist[247] =
    {   0,
        4,    4,   12,   12,   16,   16,   20,   20,   77,   74,
       76,   75,   76,    1,   74,   76,   73,   76,   73,   76,
       75,   76,    3,   73,   76,    1,   73,   76,   69,   73,
       76,   73,   76,   32,   73,   76,   73,   76,   73,   76,
       73,   76,   73,   76,   73,   76,   73,   76,   73,   76,
       73,   76,   73,   76,   73,   76,   44,   73,   76,   42,
       73,   76,   73,   76,   73,   76,   73,   76,   73,   76,
       71,   73,   76,   37,   73,   76,   73,   76,   73,   76,
       73,   76,   73,   76,   73,   76,   73,   76,   73,   76,
       73,   76,   73,   76,   45,   73,   76,   43,   73,   76,

       73,   76,   73,   76,   73,   76,   73,   76,    4,   76,
        5,   75,   76,    1,    4,   76,    6,   76,   12,   76,
       13,   75,   76,    1,   12,   76,   14,   76,   16,   76,
       17,   75,   76,    1,   16,   76,   18,   76,   20,   76,
       21,   75,   76,    1,   20,   76,   22,   76,   36,   76,
        1,   36,   76,   35,   36,   76,   36,   76,   36,   76,
       65,   76,    1,   65,   76,   64,   65,   76,   65,   76,
       75,    1,    2,   75,   69,   66,   46,   59,   55,   57,
       38,   24,   26,   28,   30,   68,   53,   49,   51,   70,
       67,   60,   56,   58,   39,   25,   27,   29,   31,   54,

       50,   52,    4,    5,   75,    2,    4,    6,   12,   13,
       75,    2,   12,   16,   17,   75,    2,   16,   20,   21,
       75,    2,   20,   35,   69,   23,   61,   47,   72,   23,
       48,   72,   19,    7,   15,   11,    8,   63,    9,   10,
       63,   62,   34,   33,   40,   41
    } ;

static yyconst short int yy_accept[270] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        5,    6,    7,    8,    9,    9,    9,    9,    9,   10,
       12,   14,   17,   19,   21,   23,   26,   29,   32,   34,
       37,   39,   41,   43,   45,   47,   49,   51,   53,   55,
       57,   60,   63,   65,   67,   69,   71,   74,   77,   79,
       81,   83,   85,   87,   89,   91,   93,   95,   98,  101,
      103,  105,  107,  109,  111,  114,  117,  119,  121,  124,
      127,  129,  131,  134,  137,  139,  141,  144,  147,  149,
      151,  154,  157,  159,  161,  163,  166,  169,  171,  172,
      173,  174,  174,  174,  175,  176,  176,  176,  176,  177,

      177,  177,  178,  178,  178,  179,  179,  179,  180,  181,
      182,  183,  184,  185,  186,  186,  187,  187,  187,  187,
      188,  188,  189,  189,  189,  189,  189,  189,  189,  190,
      190,  191,  191,  191,  192,  192,  192,  192,  193,  193,
      193,  194,  195,  196,  197,  198,  199,  200,  200,  200,
      200,  201,  202,  202,  202,  202,  202,  202,  202,  203,
      203,  204,  206,  208,  209,  210,  212,  214,  215,  217,
      219,  220,  222,  224,  225,  225,  225,  225,  225,  225,
      225,  225,  226,  226,  226,  226,  226,  226,  226,  227,
      227,  227,  228,  228,  228,  229,  229,  229,  230,  230,

      230,  230,  230,  230,  231,  231,  231,  232,  232,  232,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  234,
      234,  235,  236,  237,  237,  237,  237,  237,  238,  238,
      238,  238,  238,  239,  239,  239,  239,  240,  240,  240,
      240,  241,  241,  241,  241,  241,  242,  242,  242,  242,
      242,  242,  242,  242,  243,  243,  243,  243,  243,  244,
      244,  245,  245,  245,  245,  245,  246,  247,  247
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    7,    7,    8,    7,    9,   10,
       11,   12,   12,   12,    7,    7,    7,    1,    1,   13,
       14,   15,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   16,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   16,   16,   38,   16,
        1,    1,    1,    1,    1,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   16,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   16,   16,
       38,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    2,    3,    1,    4,    4,    4,    1,    4,    4,
        4,    4,    1,    1,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst short int yy_base[289] =
    {   0,
        0,    1,   14,    0,   52,    0,   88,   89,   92,   93,
       96,   97,  110,  111,  114,  115,  118,  119,  653,  654,
      132,  644,  654,    3,  134,  654,  643,  647,  146,  148,
      166,  152,  180,  131,  207,  146,  140,   68,  164,  161,
      162,   90,  173,  171,  187,  196,  646,  629,  209,  116,
      219,  619,  246,  169,  628,  620,  617,  610,  654,  140,
      198,  232,  625,    0,  235,  633,  637,    0,  240,  631,
      654,    0,  247,  630,  654,    0,  248,  629,  654,  654,
      628,  632,  601,  616,  654,  624,  654,  598,  249,  622,
      654,    5,  197,  261,  626,  280,  240,  269,  654,  263,

      200,  250,  269,  276,  273,  280,  277,  283,  286,  287,
      654,  654,  654,  654,  298,  294,  297,  306,  310,  308,
      309,  296,  320,  318,  322,  331,  328,  337,  335,  341,
      625,  594,  365,  654,  596,  590,  604,  654,  594,  585,
      654,  654,  654,  654,  654,  654,  654,  604,  592,  599,
      654,  654,  597,  589,  583,  248,  580,  370,  654,  581,
        0,  265,    0,  610,    0,  329,    0,    0,  356,    0,
        0,  373,    0,  609,  565,  538,  545,  375,  555,  552,
      389,  551,  538,  354,  372,  384,  385,  386,  357,  388,
      392,  358,  395,  406,  399,  402,  405,  409,  413,  518,

      527,  521,  520,  654,  475,  467,  654,  438,  438,  654,
      429,  415,  407,  412,  407,  439,  399,  419,  420,  421,
      427,  428,  430,  434,  440,  360,  355,  654,  346,  336,
      337,  306,    4,  437,  441,  449,  451,  280,  268,  254,
      654,  271,  264,  244,  239,    6,  452,  453,  203,  193,
      192,  173,  159,  654,  136,  460,  110,  114,  654,  111,
      654,  461,   62,  463,   73,  462,  654,  654,  496,  502,
      508,  514,  520,  526,  532,  537,  543,  549,  555,  561,
      566,  572,  578,  581,  587,  593,  599,  605
    } ;

static yyconst short int yy_def[289] =
    {   0,
      269,  269,  268,    3,  268,    5,  270,  270,  271,  271,
      272,  272,  273,  273,  274,  274,  275,  275,  268,  268,
      268,  268,  268,  276,  276,  268,  268,  268,  276,  276,
      276,  276,   32,   32,   32,   31,   32,   32,   32,   32,
       32,   32,   32,   32,   31,   32,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  277,  268,  277,  268,  278,  268,  278,
      268,  279,  268,  279,  268,  280,  268,  280,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  276,   32,  276,  268,  281,   32,  268,  268,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
      268,  268,  268,  268,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   31,   32,   32,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      277,  268,  277,  268,  278,  268,  278,  279,  268,  279,
      280,  268,  280,  268,  268,  268,  268,  276,  282,  283,
      281,  268,  181,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  282,  276,  283,   32,   32,   32,
       32,   32,   32,   32,   32,  268,  268,  268,  268,  268,
      268,  268,  284,   32,   32,   32,   32,  268,  268,  268,
      268,  268,  268,  285,  286,  284,   32,   32,  268,  268,
      287,  288,  285,  268,  286,   32,  268,  287,  268,  288,
      268,   32,  268,   32,  268,   32,  268,    0,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yyconst short int yy_nxt[693] =
    {   0,
      268,  268,   21,   21,   92,   92,   92,   92,  244,  245,
      268,  268,   22,   22,   23,   24,   25,   26,   23,   23,
       23,   23,   23,   23,   23,   23,   27,   23,   28,   29,
       30,   31,   32,   33,   34,   29,   29,   35,   36,   37,
       38,   39,   29,   40,   41,   42,   29,   43,   44,   45,
       46,   29,   23,   23,   21,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   27,   23,   47,   23,   48,   49,
       50,   51,   52,   23,   23,   53,   54,   55,   56,   23,
       23,   57,   58,   59,   23,   60,   61,   62,   63,   23,
       65,   65,  120,  267,   69,   69,  265,   93,   73,   73,

       66,   66,   67,   67,   70,   70,   71,   71,   74,   74,
       75,   75,   77,   77,   93,  261,   21,   21,  259,   93,
       21,   21,   78,   78,   79,   79,   81,   81,   82,   82,
       86,   86,   87,   87,   89,   92,   94,   83,   83,  263,
      136,  254,   84,   84,   90,  137,   90,  268,  268,  268,
      268,   88,   88,  268,  268,   93,  154,  119,  110,   96,
       93,   96,   93,  254,   93,   96,   97,   98,   98,   93,
      133,  133,   93,  118,  155,  156,  103,  261,   93,   96,
       99,  104,  100,  134,  121,   93,   93,  122,   93,  124,
       93,   93,  101,   93,  123,  127,  259,   93,  102,  105,

       93,  106,   93,   93,  107,  128,  108,  125,  126,   93,
      133,  133,  130,  129,  109,  111,  112,  113,  114,   93,
       93,   93,  157,  134,   93,   93,   93,  115,  257,  186,
      143,   93,  158,  133,  133,  135,   93,  162,  138,  116,
      139,  117,  166,  140,  254,  141,  134,   90,  254,  169,
      172,   89,   90,  142,  144,  145,  146,  147,  159,   90,
       90,   90,   92,   94,   93,  210,  148,  162,  252,   93,
       98,   98,  184,   90,   93,  251,  143,   90,  210,   93,
      149,  178,  178,   99,  179,  180,  181,   93,  181,  181,
      181,  181,   93,   93,  182,  188,  185,   93,   93,  250,

       93,   93,   93,  187,   93,   93,   93,   93,  110,   93,
       93,   93,   93,  189,  190,   93,   93,  249,   93,  243,
       93,   93,   93,   93,  191,   93,   93,   93,  192,  110,
       93,  166,   93,   93,   93,   93,  193,   93,   93,   93,
      195,   90,   93,  194,   93,  196,   93,   93,  198,   93,
      242,   93,   93,   93,  197,   93,  241,   93,  169,   93,
       93,  198,  199,   93,   93,   93,  133,  133,   90,   93,
       93,  133,  133,  110,  240,  172,  178,  178,   93,  134,
      239,   93,   93,  218,  134,   90,   93,   93,  238,  182,
      178,  178,  219,  268,  268,  181,   93,  181,  181,  181,

      181,   93,  220,  182,  216,  110,  110,  221,   93,   93,
       93,  216,   93,   93,   93,   93,   93,   93,  198,   93,
      222,   93,  223,   93,   93,  233,   93,  232,   93,   93,
       93,   93,  110,   93,  224,   93,  231,   93,   93,  225,
      178,  178,   93,   93,   93,   93,  235,  234,   93,   93,
       93,   93,   93,  182,   93,  230,   93,   93,   93,   93,
      237,   93,  236,   93,   93,   93,   93,  229,  143,   93,
       93,  110,  248,   93,  247,   93,   93,   93,   93,  110,
       93,   93,   93,  266,   93,   93,   93,   93,  256,  262,
       93,   93,   93,  210,  228,  264,   20,   20,   20,   20,

       20,   20,   64,   64,   64,   64,   64,   64,   68,   68,
       68,   68,   68,   68,   72,   72,   72,   72,   72,   72,
       76,   76,   76,   76,   76,   76,   80,   80,   80,   80,
       80,   80,   85,   85,   85,   85,   85,   85,   93,   93,
      143,  143,   93,  161,  161,  227,  161,  226,  161,  165,
      165,   96,  165,   95,  165,  168,  168,  216,  168,  216,
      168,  171,  171,  214,  171,  213,  171,  183,  183,  183,
      183,  183,  215,  215,  215,  215,  215,  215,  217,  217,
      217,  217,  217,  217,  246,  212,  246,  253,  253,  253,
      253,  253,  253,  255,  255,  255,  255,  255,  255,  258,

      258,  258,  258,  258,  258,  260,  260,  260,  260,  260,
      260,  174,  164,  143,  211,  209,  208,  207,  143,  206,
      205,  204,  143,  203,  202,  201,  200,  131,   95,   91,
      177,   91,  176,  175,  174,   91,  173,  170,  167,  164,
      163,  160,  153,  152,  151,  150,  143,  132,  131,   95,
       91,   91,  268,   19,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268

    } ;

static yyconst short int yy_chk[693] =
    {   0,
        0,    0,    1,    2,   24,   24,   92,   92,  233,  233,
      246,  246,    1,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    8,   38,  265,    9,   10,  263,   38,   11,   12,

        7,    8,    7,    8,    9,   10,    9,   10,   11,   12,
       11,   12,   13,   14,   42,  260,   15,   16,  258,   42,
       17,   18,   13,   14,   13,   14,   15,   16,   15,   16,
       17,   18,   17,   18,   21,   25,   25,   15,   16,  257,
       50,  255,   15,   16,   21,   50,   25,   29,   29,   30,
       30,   17,   18,   32,   32,   34,   60,   37,   34,   29,
       34,   30,   36,  253,   37,   32,   30,   31,   31,   37,
       54,   54,   36,   36,   60,   60,   32,  252,   36,   31,
       31,   32,   31,   54,   39,   40,   41,   40,   39,   43,
       40,   41,   31,   39,   41,   44,  251,   43,   31,   33,

       44,   33,   43,   45,   33,   44,   33,   43,   43,   33,
       49,   49,   46,   45,   33,   35,   35,   35,   35,   45,
       46,   93,   61,   49,  101,   46,   93,   35,  250,  101,
      249,   35,   61,   62,   62,   49,   35,   65,   51,   35,
       51,   35,   69,   51,  245,   51,   62,   65,  244,   73,
       77,   89,   69,   51,   53,   53,   53,   53,   62,   73,
       77,   89,   94,   94,   97,  156,   53,  162,  243,   97,
       98,   98,   97,   94,  102,  242,  240,  162,  156,  102,
       53,   96,   96,   98,   96,   96,   96,  100,   96,   96,
       96,   96,  100,  103,   96,  104,  100,  105,  103,  239,

      104,  107,  105,  103,  106,  104,  107,  108,  106,  106,
      109,  110,  108,  107,  115,  109,  110,  238,  116,  232,
      122,  117,  115,  116,  117,  122,  117,  115,  118,  119,
      118,  166,  120,  121,  119,  118,  120,  120,  121,  119,
      123,  166,  124,  121,  123,  124,  125,  124,  126,  123,
      231,  125,  127,  128,  125,  126,  230,  127,  169,  129,
      126,  126,  127,  128,  129,  130,  133,  133,  169,  128,
      130,  158,  158,  130,  229,  172,  178,  178,  184,  133,
      227,  189,  192,  184,  158,  172,  189,  192,  226,  178,
      181,  181,  185,  181,  181,  181,  185,  181,  181,  181,

      181,  185,  186,  181,  217,  187,  188,  190,  186,  187,
      188,  215,  190,  186,  187,  188,  191,  190,  191,  193,
      193,  191,  194,  195,  193,  214,  196,  213,  195,  197,
      194,  196,  196,  198,  197,  194,  212,  199,  198,  199,
      216,  216,  199,  218,  219,  220,  220,  218,  218,  219,
      220,  221,  222,  216,  223,  211,  221,  222,  224,  223,
      225,  234,  224,  224,  225,  235,  234,  209,  208,  225,
      235,  236,  235,  236,  234,  237,  247,  248,  236,  247,
      237,  247,  248,  264,  256,  262,  266,  264,  248,  256,
      262,  266,  264,  206,  205,  262,  269,  269,  269,  269,

      269,  269,  270,  270,  270,  270,  270,  270,  271,  271,
      271,  271,  271,  271,  272,  272,  272,  272,  272,  272,
      273,  273,  273,  273,  273,  273,  274,  274,  274,  274,
      274,  274,  275,  275,  275,  275,  275,  275,  276,  276,
      203,  202,  276,  277,  277,  201,  277,  200,  277,  278,
      278,  183,  278,  182,  278,  279,  279,  180,  279,  179,
      279,  280,  280,  177,  280,  176,  280,  281,  281,  281,
      281,  281,  282,  282,  282,  282,  282,  282,  283,  283,
      283,  283,  283,  283,  284,  175,  284,  285,  285,  285,
      285,  285,  285,  286,  286,  286,  286,  286,  286,  287,

      287,  287,  287,  287,  287,  288,  288,  288,  288,  288,
      288,  174,  164,  160,  157,  155,  154,  153,  150,  149,
      148,  140,  139,  137,  136,  135,  132,  131,   95,   90,
       88,   86,   84,   83,   82,   81,   78,   74,   70,   67,
       66,   63,   58,   57,   56,   55,   52,   48,   47,   28,
       27,   22,   19,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "html2texi.l"
#define INITIAL 0
#line 2 "html2texi.l"
  /* html2texi.l: a scanner which turns html input into texinfo */ /* JMJ */
  /* See the file COPYING for copying conditions */

#include <config.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>
#include <utils.h>
#include <html2texi.h>

  char *program_name;

#define YY_STACK_USED 1
#define TAG 1
#define END_TAG 2
#define COMMENT 3
#define META 4
#define LINK 5
#define BASE 6
#define ANCHOR 7
#define IMG 8

#line 667 "lex.yy.c"

#ifndef HAVE_STRDUP
char *strdup(char *str)
{
  char *dup = (char *)malloc( strlen(str)+1 );
  if (dup) strcpy(dup,str);
  return dup;
}
#endif

#ifndef HAVE_STRNDUP
char *strndup(char *str, size_t len)
{
  char *dup    = (char *)malloc( len+1 );
  if (dup) {
    strncpy(dup,str,len);
    dup[len] = '\0';
  }
  return dup;
}
#endif


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "html2texi.l"



	int in_quotation=0, in_dt=0, a_close_brace=0;
	int in_head=0, at_html=0;
	char *a_name=NULL, *a_href=NULL, *img_src=NULL;



#line 828 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 654 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 38 "html2texi.l"
yy_push_state(TAG);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "html2texi.l"
yy_push_state(END_TAG);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "html2texi.l"
yy_push_state(COMMENT);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "html2texi.l"
fprintf(yyout,"@c "); ECHO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "html2texi.l"
{
	fprintf(yyout,"\n");
	yy_pop_state(); yy_pop_state();
	/* pop once for current state and twice for TAG */
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "html2texi.l"
in_head=1;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "html2texi.l"
{
	if (at_html) fprintf(yyout,"\n@end html\n");
	at_html=in_head=0;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "html2texi.l"
fprintf(yyout,"@settitle ");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "html2texi.l"
{
	if (!at_html) {fprintf(yyout,"\n@html\n"); at_html=1;}
	fprintf(yyout,"<meta "); yy_push_state(META);
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "html2texi.l"
ECHO;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "html2texi.l"
{
	ECHO;
	if (!in_head) {fprintf(yyout,"\n@end html\n"); at_html=0;}
	yy_pop_state(); yy_pop_state();
	/* pop once for current state and twice for TAG */
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "html2texi.l"
{
	if (!at_html) {fprintf(yyout,"\n@html\n"); at_html=1;}
	fprintf(yyout,"<link "); yy_push_state(LINK);
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "html2texi.l"
ECHO;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "html2texi.l"
{
	ECHO;
	if (!in_head) {fprintf(yyout,"\n@end html\n"); at_html=0;}
	yy_pop_state(); yy_pop_state();
	/* pop once for current state and twice for TAG */
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "html2texi.l"
{
	if (!at_html) {fprintf(yyout,"\n@html\n"); at_html=1;}
	fprintf(yyout,"<base "); yy_push_state(BASE);
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "html2texi.l"
ECHO;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "html2texi.l"
{
	ECHO;
	if (!in_head) {fprintf(yyout,"\n@end html\n"); at_html=0;}
	yy_pop_state(); yy_pop_state();
	/* pop once for current state and twice for TAG */
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "html2texi.l"
fprintf(yyout,"\n@chapter ");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 102 "html2texi.l"
fprintf(yyout,"\n@section ");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 103 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "html2texi.l"
fprintf(yyout,"\n@subsection ");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 108 "html2texi.l"
fprintf(yyout,"\n@subsubsection ");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 109 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "html2texi.l"
yy_push_state(ANCHOR);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "html2texi.l"
a_name=strndup(yytext+6,strlen(yytext)-7);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "html2texi.l"
{
	a_close_brace=1;
	a_href=strndup(yytext+6,strlen(yytext)-7);
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 117 "html2texi.l"
{
	if (a_name) {
		fprintf(yyout,"@anchor{%s}",a_name);
		free(a_name);
		a_name=NULL;
	}
	if (a_href) {
		fprintf(yyout,"@uref{%s,",a_href);
		free(a_href);
		a_href=NULL;
}
	yy_pop_state(); yy_pop_state();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 130 "html2texi.l"
/* eat unrecognized anchor attributes */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 131 "html2texi.l"
{
	if (a_close_brace) fprintf(yyout,"}");
	a_close_brace=0;
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 136 "html2texi.l"
fprintf (yyout,"@%s{",yytext);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 137 "html2texi.l"
fprintf(yyout,"}");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "html2texi.l"
fprintf (yyout,"\n@quotation\n");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 140 "html2texi.l"
fprintf (yyout,"\n@end quotation\n");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 142 "html2texi.l"
fprintf(yyout,"%s",quotation_marks(++in_quotation,0));
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 143 "html2texi.l"
fprintf(yyout,"%s",quotation_marks(in_quotation--,1));
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 145 "html2texi.l"
fprintf(yyout,"\n\n");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 146 "html2texi.l"
/* eat */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 148 "html2texi.l"
fprintf(yyout,"@*");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 150 "html2texi.l"
fprintf(yyout,"\n@format\n");
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 151 "html2texi.l"
fprintf(yyout,"\n@end format\n");
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "html2texi.l"
fprintf(yyout,"\n@enumerate\n");
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "html2texi.l"
fprintf(yyout,"\n@end enumerate\n");
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 156 "html2texi.l"
fprintf(yyout,"\n@itemize\n");
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 157 "html2texi.l"
fprintf(yyout,"\n@end itemize\n");
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 159 "html2texi.l"
fprintf(yyout,"@item ");
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 160 "html2texi.l"
/* eat */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 162 "html2texi.l"
fprintf(yyout,"\n@table\n");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 163 "html2texi.l"
fprintf(yyout,"\n@end table\n"); in_dt=0;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 165 "html2texi.l"
fprintf(yyout,"%s ", (!in_dt)?"@item":"@itemx"); in_dt=1;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 166 "html2texi.l"
in_dt=0;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "html2texi.l"
in_dt=0; fprintf(yyout,"\n");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "html2texi.l"
/* eat */
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 171 "html2texi.l"
fprintf(yyout,"@image{"); yy_push_state(IMG);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 172 "html2texi.l"
{
	fprintf(yyout,"%s",strndup(yytext+5,strlen(yytext)-6));
	free(img_src);
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 176 "html2texi.l"
{
	fprintf(yyout,"%s",strndup(yytext+4,strlen(yytext)-5));
	free(img_src);
	}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "html2texi.l"
fprintf(yyout,"}"); yy_pop_state(); yy_pop_state();
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "html2texi.l"
/* eat other name=value attributes */
	YY_BREAK
case 66:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 183 "html2texi.l"
fprintf(yyout,"@%s{",yytext);
	YY_BREAK
case 67:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 184 "html2texi.l"
fprintf(yyout,"}");
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 188 "html2texi.l"
yy_pop_state();
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 189 "html2texi.l"
fprintf(yyout,"\n");  yy_pop_state();
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 190 "html2texi.l"
yy_pop_state();
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "html2texi.l"
/* eat */
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "html2texi.l"
/* eat unrecognized tags */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 195 "html2texi.l"
ECHO;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 196 "html2texi.l"
fprintf(yyout,"\n");
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 198 "html2texi.l"
ECHO;
	YY_BREAK
#line 1360 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(TAG):
			case YY_STATE_EOF(END_TAG):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(META):
			case YY_STATE_EOF(LINK):
			case YY_STATE_EOF(BASE):
			case YY_STATE_EOF(ANCHOR):
			case YY_STATE_EOF(IMG):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 268);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 198 "html2texi.l"


int
main (int argc, char **argv)
{
	int i;
	char *name_yyout;
	char *input_suffix, *output_suffix;

	program_name=argv[0];
	input_suffix=".html";
	output_suffix=".texi";

	if (argc==1) {
		yyin = stdin;
		yylex();
		exit(EXIT_SUCCESS);
	} /* if no filename arguments */
	for (i=1; i<argc; i++) {
		if (strcmp(argv[i],"-")) {
			yyin=fopen(argv[i],"r");
		} /* argv[i] is not "-" */
		else yyin=stdin;
		if (!yyin) {
			fprintf(stderr,"%s: %s: %s\n",program_name,argv[i],strerror(errno));
			exit(errno);
		} /* !yyin */
		yylex();
		fclose(yyin);
	} /* for i indexes argv */

	return 0;
} /* main */

/*
Local Variables:
mode: c
compile-command: "make"
End:
*/
